golift/starr

- .travis.yml
- Makefile
- lidarr/lidarr.go
- radarr/radarr.go
- radarr/type.go
- readarr/readarr.go
- shared.go
- sonarr/sonarr.go
- sonarr/type.go
Updates all the quality profile methods. Adds a release profile method for Sonarr.
> New methods for quality profiles and Sonarr release profiles.

- .travis.yml
- Makefile
- http.go
- interface.go
- lidarr/lidarr.go
- lidarr/type.go
- radarr/radarr.go
- radarr/type.go
- readarr/readarr.go
- readarr/type.go
- shared.go
- sonarr/sonarr.go
- sonarr/type.go
- starr.go
This contribution adds the ability to capture sent and received payloads in a log/file.
> Add debug logging.

- starr.go
> Fix previous release.

- lidarr/lidarr.go
- radarr/radarr.go
- readarr/readarr.go
- shared.go
- sonarr/sonarr.go
- sonarr/type.go
Adds a few more feature to sonarr commands. Rename Bits to Base.
> update sonarr commands

- radarr/radarr.go
adds a function for using radarr's /movie/lookup endpoint
> #15 radarr movie lookup

- Makefile
- README.md
- mocks/apier.go
- prowlarr/prowlarr.go
- prowlarr/type.go
This small contribution adds support for Prowlarr. Only 1 method at this time. If you need more Prowlarr support, let me know!
> Add prowlarr support.

- Makefile
- http.go
- lidarr/lidarr.go
- lidarr/type.go
- radarr/radarr.go
- radarr/type.go
- readarr/readarr.go
- sonarr/sonarr.go
Adds Lookup method to all Starr apps. Compliments #16 and closes #15. 
Returns slice of pointers to objects.
> Add Lookup to all apps

- lidarr/lidarr.go
- paginate.go
- radarr/radarr.go
- readarr/readarr.go
- shared.go
- sonarr/sonarr.go
This contribution adds a filtering input to the pageable requests (history and queue).
> Add filter inputs to pageable calls.

- shared.go
- sonarr/episodefile.go
- sonarr/type.go
Closes #28 by adding the requested methods.
> Add episodeFile methods.

- sonarr/seasonpass.go
> add season pass

- radarr/tag.go
> fix: radarr tag path typo

- readarr/author.go
- readarr/book.go
Fix for https://github.com/Notifiarr/notifiarr/issues/211
> update readarr book endpoint data

- .golangci.yml
- .travis.yml
- http.go
- interface.go
- lidarr/qualityprofile.go
- radarr/customformat.go
- radarr/qualityprofile.go
- readarr/qualityprofile.go
- sonarr/episodefile.go
- sonarr/qualitydefinition.go
- sonarr/qualityprofile.go
- sonarr/releaseprofile.go
- starr.go
- starrcmd/lidarr.go
I came in to add the missing delete methods to quality profile on radarr. Then added a few more missing delete methods. Then fixed a few error lines in the files I edited. Then updated golangci-lint and fixed the lint warnings. First commit is the changes, second commit is the lint.
> Quality Profile Delete

- README.md
- http.go
- http_test.go
- interface.go
- lidarr/qualityprofile.go
- lidarr/tag.go
- lidarr/trackfile.go
- prowlarr/tag.go
- radarr/customformat.go
- radarr/exclusions.go
- radarr/importlist.go
- radarr/qualityprofile.go
- radarr/tag.go
- readarr/qualityprofile.go
- readarr/tag.go
- sonarr/delayprofile.go
- sonarr/episodefile.go
- sonarr/indexer.go
- sonarr/languageprofile.go
- sonarr/qualityprofile.go
- sonarr/releaseprofile.go
- sonarr/rootfolder.go
- sonarr/series.go
- sonarr/tag.go
Closes #55. 
@aetaric Do you need `trackFile/editor` endpoint? If yes, I'll rely on you to test it after I add it.
This contribution also changes the interface inputs. They are converted from multiple values to a singe `Request` struct. This is only partial for now, but another contribution will convert the rest at once.
> Add track file methods for lidarr.

- radarr/mediamanagement.go
- radarr/mediamanagement_test.go
- radarr/naming_test.go
- radarr/rootfolder.go
- radarr/rootfolder_test.go
- sonarr/mediamanagement.go
- sonarr/mediamanagement_test.go
- add mediamanagement
- add naming
- add rootfolder missing methods
> feat(radarr): media management

- lidarr/command.go
- sonarr/command.go
Just adding a few fields that are missing that I needed for checkrr.
> Adds fields for RescanFolder and RefreshArtist

- sonarr/command.go
Update CommandRequest type to support `EpisodeSearch` command
> [Sonarr] Update CommandRequest type to support `EpisodeSearch` command

- lidarr/notification.go
- lidarr/notification_test.go
- prowlarr/notification.go
- prowlarr/notification_test.go
- radarr/notification.go
- radarr/notification_test.go
- readarr/notification.go
- readarr/notification_test.go
> feat: add notification for other arrs

- radarr/qualityprofile.go
- radarr/qualityprofile_test.go
- add `GetQualityProfile` method
- change `AddQualityProfile` and `UpdateQualityProfile` output to return `*QualityProfile`
- add test
I changed also some `omitempty` flags I tested it out a bit and I think everything is fine, but feel free to test it yourself
> feat(radarr)!: quality profile

- radarr/movie.go
re: https://github.com/Notifiarr/notifiarr/issues/370
Anything I'm missing here? I'm tired..
> add another radarr addMovieOption

- LICENSE
- README.md
- debuglog/roundtripper.go
- starrtest/starrtest.go
Adds redaction to the debug log.
> Debuglog Updates

- lidarr/importlist.go
- prowlarr/notification.go
- prowlarr/notification_test.go
- radarr/importlist.go
- readarr/importlist.go
- sonarr/importlist.go
- sonarr/importlist_test.go
Import list was sending empty strings when it shouldn't send anything. Fixing that. Also making sure all the struct members exist.
> Import list fixes

- .github/workflows/codetests.yml
- .golangci.yml
- README.md
- shared.go
- sonarr/customformat.go
- sonarr/customformat_test.go
- sonarr/episodefile.go
- Aligns Sonarr custom formats methods with Radarr and closes #84.
- Closes #58 since everything seems fine in v4.
> Sonarr custom format alignment.

- lidarr/queue.go
- radarr/queue.go
- readarr/queue.go
- shared.go
- shared_test.go
- sonarr/queue.go
Adds queue delete methods for all four apps.
> Add queue delete methods.

- radarr/releaseprofile.go
> Add release profiles for Radarr

- .github/workflows/codetests.yml
- lidarr/manualimport.go
- lidarr/queue.go
- lidarr/track.go
- lidarr/trackfile.go
- radarr/manualimport.go
- radarr/movie.go
- radarr/movieeditor.go
- radarr/moviefile.go
- radarr/queue.go
- radarr/releaseprofile.go
- readarr/bookfile.go
- readarr/manualimport.go
- readarr/queue.go
- shared.go
- sonarr/manualimport.go
- sonarr/queue.go
- Adds queue grab for all four apps. Needs testing.
- Adds manual import methods for all four apps. Needs testing.
- Adds track.go (tracks) for Lidarr.
- Adds bookfile.go for Readarr.
- Adds moviefile.go for Radarr.
> Add queue grab and manualimport methods to all four apps.

- radarr/movie.go
> Break GetMovie api

- LICENSE
- README.md
> add link, update year

- sonarr/episode.go
Needed to add this param to filter by. Can add the others here too if wanted
> Added Filtering by EpisodeFileID

- sonarr/series.go
> Turn add series monitor option into an enum

- lidarr/mediamanagement.go
- lidarr/naming.go
- readarr/mediamanagement.go
- readarr/naming.go
- Add `Media Management` for Lidarr and Readarr.
- Add `Naming` for Readarr.
- Updating `Naming` for Lidarr.
> Add media management for lidarr and readarr, naming for Readarr.

- sonarr/parse.go
> Add Parse endpoint for Sonarr

- sonarr/series.go
- Closes #148 as soon as I can reproduce it and fix it.
- Adds two missing statistics.
> Update Sonarr Series/Season Statistics 
