golift/starr

.travis.yml, Makefile, sonarr/type.go, starr.go
Fixes a Sonarr changes and makes this library no longer backward compatible with any old version of Sonarr. At least the Release Profile type.  https://github.com/Sonarr/Sonarr/commit/deed85d2f9147e6180014507ef4f5af3695b0c61
I also added a method to make finding the correct Starr app url easier.
=> Change Sonarr Release profile struct members  'Required' and 'Ignored' to lists.

Makefile, lidarr/lidarr.go, radarr/radarr.go, radarr/type.go, readarr/readarr.go, shared.go, sonarr/sonarr.go
This updates the GetHistory and GetQueue methods on all starr apps.
They are now "all the same" and take identical inputs. This breaks backward compatibility, sorry. A few minor updates and you should be good to go.
If you use to do `GetHistory(100)` you can now do `GetHistory(100, 100)` to do the same thing. Similar for `GetQueue()`. The main difference is that you can now pass `0` to get all records. `GetHistory(0,1000)` will download all items in batches of 1000.
=> Add paginatable methods to all starr apps.

http.go, lidarr/lidarr.go, radarr/radarr.go, readarr/readarr.go, shared.go, sonarr/sonarr.go, starr.go
Compliments #14. Adds missing Fail() methods to Readarr and Lidarr. Cleans up existing methods in Sonarr and Radarr.
=> Add Fail to Lidarr and Readarr apps, clean up errors.

lidarr/tag.go, prowlarr/tag.go, radarr/tag.go, readarr/tag.go, sonarr/tag.go
- add GetTag
- add DeleteTag
- add Tag methods for Prowlarr (not very useful)
- edit UpdateTag to be aligned with api docs
=> feat: add tag resources

sonarr/delayprofile.go, sonarr/qualitydefinition.go
Hi @davidnewhall,
First part of #37, with the new features (delayprofile and qualitydefinition)
Once this is merged I'll rebase #37 with the changes in languageprofile, qualityprofile, and releaseprofile.
If that works well, then we can plan to change the other methods as well
=> feat(sonarr): add delayprofile qualitydefinition

lidarr/tag.go, lidarr/tag_test.go, prowlarr/prowlarr.go, prowlarr/tag.go, prowlarr/tag_test.go, radarr/tag.go, radarr/tag_test.go, readarr/tag.go, readarr/tag_test.go, sonarr/tag.go, sonarr/tag_test.go
PR for changes in tags across all clients:
- change methods output
- align naming convention for output
- use constant for base path and uri var to construct request
- add tests
=> feat!: tags ids to objects with tests

.golangci.yml, Makefile, starrcmd/radarr_test.go
- Move golang-ci configuration from command to dedicated config file.
- Disable funlen linters for test files
@davidnewhall this is mainly to avoid having multiple comments `//nolint:something` around the code.
If there is some other generic rule you want to implement, I can add them to this PR, or we can start with this and add rules only when/if needed.
=> build: add golangci configuration

.travis.yml
since install.goreleaser.com isn't resolved anymore, this is to update the endpoint as per https://golangci-lint.run/usage/install/
=> build: fix golangci-lint endpoint

shared.go, sonarr/series.go, sonarr/series_test.go, sonarr/type.go, test_methods.go
Hi @davidnewhall,
These the proposed changes to series:
- using a single struct for series even if some responses and some inputs can have different empty values (mainly changes AddSeries)
- in UpdateSeries remove the ID input and leverage the ID inside the struct
- add DeleteSeries. I enforced as general behaviour to remove files and not exclude from importlist. If you prefer, we can pass the two flags as inputs.
- moving time.Time type to reference in struct. I know it's not best practice to use reference instead of values for time. However, *time.Time with "omitempty" tag is really omitted in json, while time.Time is still enforced with a 0 value. This allow us to omit time.Time fields in requests.
- add series tests
- I had to move the request checks before the response checks in …
=> feat(sonarr)!: migrate series output

sonarr/mediamanagement.go, sonarr/mediamanagement_test.go, sonarr/naming.go, sonarr/naming_test.go, sonarr/rootfolder.go, sonarr/rootfolder_test.go, sonarr/sonarr.go, sonarr/type.go
This is to add the following resources to Sonarr:
- MediaManagement: Only read and update, since it cannot be created or deleted.
- Naming: Same as previous one.
- RootFolder: no edit. To change root folder the process should probably be create new one > move series > delete old one. It cannot be done via a single API.
=> feat(sonarr): add media management tab resources

shared.go, sonarr/indexer.go, sonarr/indexer_test.go, sonarr/indexerconfig.go, sonarr/indexerconfig_test.go
Hi @davidnewhall,
I'm creating this draft to have few feedbacks before continuing. I'm trying to implement the indexer methods for sonarr.
while the /indexer/config endpoint it's pretty straightforward, I'd like to have your opinion on a couple of points for the /indexer endpoint:
- How to address the `Value` field of `Field` struct? The type of this field isn't consistent, should we pass a generic interface? or is it better to have type assertion based on the actual type? I'd prefer to go with the second option. Hence, I tried to implement a draft with the function `correctIndexerFieldsValue` that could be improved if we follow this approach. I even thought of using a generic type assertion switch, but that could lead to wrong assertion for int/float.
- Should we separate input struct …
=> feat(sonarr): add indexer methods

Makefile, lidarr/system.go, prowlarr/system.go, radarr/system.go, readarr/system.go, sonarr/system.go
Closes #67. 
Updates and alphabetizes structs for `system/status`.
=> Update system/status structs

.golangci.yml, go.mod, go.sum, pointers.go, radarr/importlist.go, radarr/movie.go, radarr/movieeditor.go, radarr/movieeditor_test.go, shared.go, test_methods.go
Adds movie editor endpoint.
Adds movie delete and bulk delete endpoints.
Closes #68. @NCRoxas, can you test this?
```go
edit := &radarr.BulkEdit{
MovieIDs:    []int64{7, 3},
Monitored:   starr.True(),
DeleteFiles: starr.False(),
}
movies, err := r.EditMovies(edit)
```
=> Add movie editor endpoints

radarr/naming.go, radarr/naming_test.go, sonarr/naming.go, sonarr/naming_test.go, test_methods.go
Adds `config/naming` endpoints to Radarr. Pretty much copy/paste from Sonarr.
=> Add config/naming to Radarr

.golangci.yml, radarr/naming_test.go, readarr/author.go, readarr/book.go, readarr/calendar.go, readarr/calendar_test.go, shared.go, sonarr/calendar.go, sonarr/calendar_test.go, sonarr/episode.go, sonarr/episodefile.go
Closes half of #66. I'm only going to do Sonarr and Readarr in this 1 PR to keep it smaller. Will make another one for the other two apps.
Cleans up `Book`, `Author`, and `Episode` types. Probably easier to look at without white-space changes: https://github.com/golift/starr/pull/71/files?w=1
=> Add Calendar methods: sonarr & readarr

radarr/movie.go, shared.go
Adds a few missing fields, fixes `ratings` field in Movie type. Replaces `AddMovieOutput` with `Movie` and adds a proper output to `UpdateMovie()`.
=> Fix radarr movie types.

sonarr/notification.go, sonarr/notification_test.go
=> feat(sonarr): add notification

radarr/delayprofile.go, radarr/delayprofile_test.go, sonarr/delayprofile.go, sonarr/delayprofile_test.go
- add radarr delayprofile
- add sonarr delayprofile tests
- update omitempty tags of sonarr delayprofile
To keep in mind: response of create delayprofile doesn't take into account the "order" field sent on creation. This can only be edited after via update.
=> feature(radarr): delay profile

radarr/movie.go
Closes #76. Ref: 
https://github.com/Radarr/Radarr/blob/627ab64fd023269c8bedece61e529329600a3419/src/Radarr.Api.V3/Movies/MovieModule.cs#L218
Makes it look like `DeleteMovie`...
=> Removes moveFiles default from updateMovie endpoints and makes it user-selectable.

radarr/indexer.go, radarr/indexer_test.go, radarr/indexerconfig.go, radarr/indexerconfig_test.go, radarr/restriction.go, radarr/restriction_test.go
- add indexer methods
- add indexer config methods
- add restriction methods
Indexer is the same as sonarr. However I noticed that is a bit different in lidarr. For now, I think it'll be better to keep them separated.
=> feat(radarr): indexer

lidarr/downloadclient.go, lidarr/downloadclient_test.go, lidarr/downloadclientconfig.go, lidarr/downloadclientconfig_test.go, lidarr/remotepathmapping.go, lidarr/remotepathmapping_test.go, prowlarr/downloadclient.go, prowlarr/downloadclient_test.go, radarr/downloadclient.go, radarr/downloadclient_test.go, radarr/downloadclientconfig.go, radarr/downloadclientconfig_test.go, radarr/remotepathmapping.go, radarr/remotepathmapping_test.go, readarr/downloadclient.go, readarr/downloadclient_test.go, readarr/downloadclientconfig.go, readarr/downloadclientconfig_test.go, readarr/remotepathmapping.go, readarr/remotepathmapping_test.go, shared.go, sonarr/remotepathmapping.go, sonarr/remotepathmapping_test.go
- add downloadclientconfig (radarr,readarr,lidarr)
- add remotepathmapping (radarr,readarr,lidarr)
- add downloadclient (radarr,readarr,lidarr,prowlarr)
Since remotepathmapping is the same in each arr, we can put the struct definition in the starr package. @davidnewhall what do you think? should we keep each file separate, or should we group the struct definition in one place?
the other 2 resources change a bit between different arr
=> feat: download client

radarr/customformat.go, radarr/customformat_test.go, shared.go
per #84, here is the PR. Main changes are:
- `CustomFormat` struct has been split into `CustomFormatInput` and `CustomFormatOutput`
- `CustomFormatSpec` has been split into `CustomFormatInputSpec` and `CustomFormatOutputSpec`. One of the main point here is that input won't contain `ImplementationName` and `InfoLink` anymore
- `CustomFormatField` has been removed in favor of `starr.FieldInput` and `starr.FieldOutput`. Which is the other main point of the previous one
- `ID` field changed type from `int` to `int64`
- `ImplementationName` and `InfoLink` fields to PascalCase
- `UpdateCustomFormat` takes the `ID` directly from `CustomFormatInput`. On this one, I don't know if there is any use case in which the two inputs would actually differ.
- added `GetCustomFormat` method
Thoughts?
=> feat(radarr)!: update customformat methods

lidarr/album.go, readarr/book.go, sonarr/series.go, sonarr/series_test.go
=> do not hard code moveFiles

Makefile, lidarr/indexer.go, lidarr/indexer_test.go, lidarr/indexerconfig.go, lidarr/indexerconfig_test.go, prowlarr/indexer.go, prowlarr/indexer_test.go, readarr/indexer.go, readarr/indexer_test.go, readarr/indexerconfig.go, readarr/indexerconfig_test.go
- add indexer (readarr, lidarr)
- add indexerconfig (readarr, lidarr)
- add prowlarr indexer. 
First two were pretty straightforward, I hope I haven't missed anything.
For the latest, I tried to run simple test and it worked. However, I think that if we merge this, we'll have to work again on prowlarr's indexer in the future.
If you don't like the prowlarr code, I can remove it from this PR.
=> feat: indexer

sonarr/importlist.go, sonarr/importlist_test.go
This is to add importlist endpoint to sonarr. I probably won't make new PRs for some time, but I'll try come back with the new year
=> feat(sonarr): add importlist

shared.go, sonarr/episode_test.go
The TLS Config passed into the http client gets overwritten; this fixes it.
=> preserve client transport in debug log

README.md, lidarr/album.go, lidarr/artist.go, lidarr/history.go, lidarr/queue.go, radarr/blocklist.go, radarr/downloadclient.go, radarr/exclusions.go, radarr/history.go, radarr/importlist.go, radarr/indexer.go, radarr/queue.go, readarr/author.go, readarr/book.go, readarr/history.go, readarr/queue.go, shared.go, sonarr/blocklist.go, sonarr/downloadclient.go, sonarr/history.go, sonarr/importlist.go, sonarr/indexer.go, sonarr/queue.go, sonarr/seasonpass.go
Cleans up a few pieces and adds a couple missing methods in Lidarr and Readarr.
=> Cleanup, couple new methods for lidarr and Readarr.

.github/workflows/codetests.yml, lidarr/customformat.go, lidarr/naming.go, lidarr/qualitydefinition.go, radarr/qualitydefinition.go, shared.go
Adds naming and custom format methods to lidarr. And quality definitions. This also renames a method in lidarr (it was wrong).
=> Add lidarr naming and custom formats

debuglog/roundtripper.go
- Adds elapsed time to request for https://github.com/Notifiarr/notifiarr/issues/601
=> add elapsed to debuglog

sonarr/naming.go, sonarr/naming_test.go
- re: https://github.com/Sonarr/Sonarr/pull/6941
=> add new sonarr custom naming format
